config/routes.rb
Rails.application.routes.draw do
  root                'static_pages#home'
  get    'help'    => 'static_pages#help'
  get    'about'   => 'static_pages#about'
  get    'contact' => 'static_pages#contact'
  get    'signup'  => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  resources :users
end

app/models/activity.rb
class Activity < ActiveRecord::Base
  belongs_to :user
end

app/models/course.rb
class Course < ActiveRecord::Base
  include Logs

  has_many :user_courses, dependent: :destroy
  has_many :course_subjects, dependent: :destroy
  has_many :users, through: :user_courses, dependent: :destroy
  has_many :subjects, through: :course_subjects, dependent: :destroy
  has_many :tasks, through: :subjects
  scope :recent, ->{order created_at: :desc}
  scope :active_course, ->{where "closed = ?", Settings.courses.active}

  validates :name, presence: Settings.courses.is_present,
    length: {minimum: Settings.courses.min_c, maximum: Settings.courses.max_c}
  before_create {self.closed = true}

  def date_duration
    self.subjects.inject(0){|total_date, subject| total_date + subject.date_duration}
  end

  def has_trainee? user
    self.users.include? user
  end

  def has_member? user
    has_trainee?(user) || has_supervisor?(user)
  end

  def expired_date
    self.created_at + date_duration.day
  end

end

app/models/course_subject.rb
class CourseSubject < ActiveRecord::Base
  belongs_to :course
  belongs_to :subject
  has_many :user_subjects
end

app/models/subject.rb
class Subject < ActiveRecord::Base
  include Logs
  has_many :user_subjects, dependent: :destroy
  has_many :course_subjects, dependent: :destroy
  has_many :tasks, dependent: :destroy
  has_many :user_tasks, through: :tasks
  has_many :courses, through: :course_subjects
  has_many :users, through: :user_subjects
  scope :recent, ->{order created_at: :desc}

  accepts_nested_attributes_for :tasks, allow_destroy: true,
    reject_if: proc {|attribute| attribute[:name].blank?}
  validates :name, presence: Settings.subjects.is_present,
    length: {minimum: Settings.subjects.min_c, maximum: Settings.subjects.max_c}
end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :subject
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessor :remember_token
  has_many :user_subjects
  has_many :user_tasks
  has_many :activities
  before_save { self.email = email.downcase }
  validates :name,  presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true
  def self.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end
  def self.new_token
    SecureRandom.urlsafe_base64
  end
  def remember
    self.remember_token = User.new_token
    update_attributes remember_digest: User.digest(remember_token)
  end
  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end
  def forget
    update_attributes remember_digest: nil
  end
end

app/models/user_course.rb
class UserCourse < ActiveRecord::Base
  belongs_to :user
  belongs_to :course

  after_create :init_user_subjects
  after_create :notify_assigned_email
  after_destroy :remove_user_subjects
  after_destroy :notify_unassigned_email

  def remove_user_subjects
    self.course.subjects.each do |subject|
      UserSubject.find_by(user_id: self.user_id, subject_id: subject.id).destroy
    end
  end

  def notify_unassigned_email
    EmailUnassignTrainees.perform_async self.user_id, self.course_id
  end
end

app/models/user_subject.rb
class UserSubject < ActiveRecord::Base
  belongs_to :user
  belongs_to :course_subject
end

app/models/user_task.rb
class UserTask < ActiveRecord::Base
  belongs_to :user
  belongs_to :task
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :init_course, only: :show
  load_and_authorize_resource :course

  def show
  end

  private
  def init_course
    @course = Course.find params[:id]
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      params[:session][:remember_me] == '1' ? remember(user) : forget(user)
      redirect_to user
    else
      flash.now[:danger] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    log_out if logged_in?
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end

  def contact
  end
end

app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController
  before_action :init_course, only: [:show, :update]
  before_action :init_user_subject, only: [:show, :update]
  before_action :init_course_subject, only: [:show, :update]
  load_and_authorize_resource :course

  def show
  end

  def update
    if @user_subject.update user_subject_params
      flash[:success] = t "views.messages.update_successfully"
      redirect_to [@course, @user_subject.subject]
    else
      flash[:danger] = t "views.messages.failed"
      render :show
    end
  end

  private
  def init_course
    @course = Course.find params[:course_id]
  end

  def init_user_subject
    @user_subject = UserSubject.find_by user_id: current_user.id,
      subject_id: params[:id],course_id: params[:id]
  end

  def init_course_subject
    @course_subject = CourseSubject.find_by course_id: params[:course_id],
      subject_id: params[:id]
  end

  def user_subject_params
    params.require(:user_subject).permit user_tasks_attributes: [:id, :finished]
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find params[:id]
  end

  def new
    @user = User.new
  end

 def create
    @user = User.new user_params
    if @user.save
      log_in @user
      flash[:success] = "Welcome to the Sample App!"
      redirect_to @user
    else
      render 'new'
    end
  end

  private

    def user_params
      params.require(:user).permit :name, :email, :password,
                                   :password_confirmation
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

  # Returns the full title on a per-page basis.       # Documentation comment
  def full_title(page_title = '')                     # Method def, optional arg

    if page_title.empty?                              # Boolean test
      t :title                                       # Implicit return
    else
      page_title + " | " + t(:title)                  # String concatenation
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end
  def remember(user)
    user.remember
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end
  def current_user
    if (user_id = session[:user_id])
      @current_user ||= User.find_by(id: user_id)
    elsif (user_id = cookies.signed[:user_id])
      user = User.find_by(id: user_id)
      if user && user.authenticated?(cookies[:remember_token])
        log_in user
        @current_user = user
      end
    end
  end
  def logged_in?
    !current_user.nil?
  end
  def forget(user)
    user.forget
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end
  def log_out
    forget(current_user)
    session.delete :user_id
    @current_user = nil
  end
end

app/helpers/users_helper.rb
module UsersHelper

  # Returns the Gravatar for the given user.
  def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/courses/show.html.erb
<% provide :title, @course.name %>
<br>
<h1 class="text-center text-success">
  <b><%= t("views.course").capitalize %> : </b><%= @course.name %>
</h1>

<h2 class="text-center">
  <span class="label label-<%= @course.closed ? "danger" : "success" %>">
    <%= t @course.closed ? "views.messages.closed" : "views.messages.opening" %>
  </span>
</h2>
<hr>
<div class="text-center">
  <% @course.course_subjects.each do |course_subject| %>
     <%= link_to "Coure_subject",course_subject_path(@course, course_subject.subject), :class=>"btn btn-subject" %>
      <%= current_user.user_subjects.finished(course_subject.subject).any? ||
        course_subject.closed ? "btn-danger" : "btn-success" %>"
      <%= course_subject.subject.name %>
      <br>
      <%= pluralize course_subject.subject.date_duration, t("views.unit.day") %>
    <span class="glyphicon glyphicon-arrow-right"></span>
  <% end %>
</div>
<br>
<div>
  <div class="container">
    <table class="table">
      <tr>
        <td class="text18px text-info col-md-2">
          <b class="pull-right"><%= t "courses.description" %> :</b>
        </td>
        <td>
          <%= @course.description %>
        </td>
      </tr>
      <tr>
        <td class="text18px text-info col-md-2">
          <b class="pull-right">
            <%= pluralize @course.users.count, t("trainee").capitalize %>:</b>
        </td>
        <td>
          <% @course.users.each do |user| %>
            <span class="glyphicon glyphicon-user text-info"></span>&nbsp;
            <%= link_to user.name, user %>
            &nbsp; &nbsp; &nbsp; &nbsp;
          <% end %>
        </td>
      </tr>
      <tr>
        <td class="text18px text-info col-md-2">
          <b class="pull-right"><%= t "course.start_date" %> :</b>
        </td>
        <td>
          <%= l @course.created_at, format: :short_date %>
        </td>
      </tr>
      <tr>
        <td class="text18px text-info col-md-2">
          <b class="pull-right"><%= t "course.time_duration" %> :</b>
        </td>
        <td>
          <%= pluralize @course.date_duration, t("views.unit.day") %>
        </td>
      </tr>
    </table>
  </div>
</div>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <a href="http://railstutorial.org/">Framgia TMS</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      <li><a href="http://news.railstutorial.jp/">News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "sample app", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "Help", help_path %></li>
        <% if logged_in? %>
          <li><%= link_to "Users", '#' %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Settings", '#' %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: "delete" %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag "application", media: "all",
                                           "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/about.html.erb
<% provide(:title, 'About Us') %>
<h1>About Us</h1>
<p>
 Vi muc tieu xa hoi chu nghia 
</p>

app/views/static_pages/contact.html.erb
<% provide :title, t("views.pages.contact") %>
<h1>
  <strong><%= t "views.pages.contact" %></strong>
</h1>

app/views/static_pages/help.html.erb
<% provide(:title, 'Help') %>
<h1>Help</h1>
<p>
  please ask anything
</p>

app/views/static_pages/home.html.erb
<% provide(:title, 'Home') %>
<h1>Framgia TMS</h1>
<p>
    This is the home page for the
    <a href="http://railstutorial.jp/">Ruby on Rails Tutorial</a>
    sample application.
</p>

app/views/subjects/show.html.erb
<% provide :title, "#{@course.name} > #{@course_subject.subject.name}" %>
<h2>
  <%= link_to @course.name, @course %>
  <span class="glyphicon glyphicon-chevron-right"></span>
  <span class="text18px"><%= @course_subject.subject.name %></span>
</h2>
<br>
<div>
  <table class="table">
    <tr>
      <td class="text18px text-info col-md-2">
        <b class="pull-right">
          <%= t "messages.subjects.description" %> :
        </b>
      </td>
      <td>
        <%= @course_subject.subject.instruction %>
      </td>
    </tr>
    <tr>
      <td class="text18px text-info col-md-2">
        <b class="pull-right">
          <%= t "messages.subjects.time_duration" %> :
        </b>
      </td>
      <td >
        <%= pluralize @course_subject.subject.date_duration, t("views.unit.day") %>
      </td>
    </tr>
  </table>
</div>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for @user_subject, url: [@course, @course_subject.subject] do |f| %>
      <%= render "shared/error_messages", object: f.object %>
      <div class="field">
        <table class="table">
          <tbody>
            <%= f.fields_for :user_tasks do |builder| %>
              <tr>
                <td class="col-md-1">
                  <%= builder.check_box :finished, checked: builder.object.finished?,
                    disabled: builder.object.finished? %>
                </td>
                <td>
                  <span class="label <%= builder.object.finished ?
                    "label-success" : "label-danger" %>">
                    <%= builder.object.task.name %>
                  </span>
                  <span><%= builder.object.task.description %></span>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
      <%= f.submit t("views.actions.finish"), class: "btn btn-success" %>
    <% end %>
  </div>
</div>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for @user do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Create my account", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<h1>
  <%= gravatar_for @user %>
  <%= @user.name %>
</h1>